### ISSUE TITLE
Using tax_myPHAGE for viruses reconstructed from metagenomes

### ISSUE THREAD

**Issue by asierFernandezP** [amillard/tax_myPHAGE#16]
Thanks for the great tool! I am currently running tax_myPHAGE on a set of viral genomes reconstructed from metagenomic samples from the human gut. I was wondering if you have any recommendation when applying tax_myPHAGE for this kind of data. E.g. would you recommend keeping only the taxonomy for those viruses with at least medium/high completeness assigned by CheckV? How does the tool behave with viral genomes with lower/medium completeness?

Thank you!
Asier

**Comment by amillard** [comment]
Hi, 
It assumes the genomes are complete, so incomplete genomes will cause the intergenomic similarity values to be inaccurate . The shorter the more inaccurate , as rule of thumb.  Cases around boundaries will become a problem  eg 94.9 v 95 for new or existing species.  But it would get you the correct genus.  I would nt run it with geomes predicted < 70% complete by checkV or be wary of the results 
we have an update coming that substantially increase the speed for cases like this , where you want to run lots of samples very quickly

**Comment by asierFernandezP** [comment]
Thank you very much Andrew! I will then retrieve the taxonomy (probably genus-level) only for those viruses above certain quality threshold. 

One extra question: I see sometimes the following message in the output file: "The number of expected genera is different from the predicted number of genus clusters. It will require more manual curation". Would you avoid using the taxonomy predicted for these cases or still use it at  certain taxonomic level?

**Comment by amillard** [comment]
the warning is because of the ICTV taxonomy, with the move to genomic cutoffs there are: 1) genera/species that already existed that don't confirm to these newer guidance and havent been updated 2) edge cases where other methods were used to calculate ANI other that might not take into account identity across the entire genome, leading to values just above (or below) the cutoff values of 70 and 95.  The warning is highlighting one of these - that the existing genus/species are not consistent with current standard cutoffs.  Details of why it might be inconsistent would be in the original taxonomy proposal - it not possible to know with manual checking. Hence the warning 
I would report with a * may be inaccurate

You could always submit a taxonomy proposal for next year to resolve and/or correct the issue, for future versions of ICTV...... :-) not that is solves you current problem
